# api call for list
###

GET http://127.0.0.1:8000/turf/
Accept: application/json
Authorization: Basic admin:1234
#api call for add
###

POST http://127.0.0.1:8000/turf/
Content-Type: application/json
Authorization: Basic admin:1234
{
    "name":"Green Arena",
    "turf_type":"Football",
    "location":"Thrissur",
    "price":800,
    "contact_email":"green@gmail.com"

},

#
###

GET http://127.0.0.1:8000/turf/1/
Accept: application/json
Authorization: Basic admin:1234
#api call for update 
###
PUT http://127.0.0.1:8000/turf/1/
Content-Type: application/json
Authorization: Basic admin:1234
{
    "id":1,
    "name":"Sports Hub",
    "turf_type":"Cricket",
    "location":"Kochi",
    "price":1200,
    "contact_email":"sp@gmail.com"
}

#
###

DELETE http://127.0.0.1:8000/turf/1/
Content-Type: application/json
Authorization: Basic admin:1234
{
    "id":1
}



#api call for llist in serializer
###

GET http://127.0.0.1:8000/v2/turf/2/
Accept: application/json
Authorization: Basic admin:Ashwin@123
#api call for add
###

POST http://127.0.0.1:8000/v2/turf/2/
Content-Type: application/json
Authorization: Basic admin:As123

{
    "name":"Play Zone",
    "turf_type":"Badminton",
    "location":"Trivandrum",
    "price":700,
    "contact_email":"zone@gmail.com"
}

#
###

PUT http://127.0.0.1:8000/v2/turf/2/
Content-Type: application/json

{
    "id": 2,
    "name": "Super Soccer",
    "turf_type":"Football",
    "location":"MBBS",
    "price": 600,
    "contact_email":"super@gmail.com"
}

#
###

POST http://127.0.0.1:8000/v2/admin-register/
Content-Type: application/json

{
    "username":"As123",
    "password":"Ashwin@123",
    "email":"ashwin@gmail.com"
}

#api call for list
###

GET http://127.0.0.1:8000/appointment/
Accept: application/json

#
###

POST  http://127.0.0.1:8000/appointment/
Content-Type: application/json

{
    "customer_name":"Arul",
    "phone":"12345",
    "turf":2,
    "date":"2025-02-09",
    "purpose":"football"

}

#api call for list
###

GET http://127.0.0.1:8000/appointment/1/
Accept: application/json

#api call for delete
###

DELETE http://127.0.0.1:8000/appointment/1/
Content-Type: application/json

{
    "id":2
}

#api call for update
###
PUT http://127.0.0.1:8000/appointment/1/
Content-Type: application/json

{
    "customer_name":"Arnold",
    "phone":"12490",
    "turf":2,
    "date":"2028-02-09",
    "purpose":"cricket"

}

#
###

POST http://127.0.0.1:8000/turf/signup/
Content-Type: application/json

{
    "username":"ayu123",
    "email":"ayu@gmail.com",
    "password":"ayush$56"
}

# listing all booked records api
###
GET http://127.0.0.1:8000/turf/booking/
Accept: application/json
Authorization: Basic drf:ayush@56

#api for booking turf
###
POST http://127.0.0.1:8000/turf/booking/
Content-Type: application/json
Authorization: Basic drf:password@123

{
   "name":"liminar",
   "location":"thrisue",
   "email":"luminar@gmail.com",
   "phone_number":"8128380834",
   "duration":"07:30 AM"
}


#api for detail for record
###
GET http://127.0.0.1:8000/turf/booking/2/
Accept: application/json
Authorization: Basic drf:password@123

# api for updating record
###
PUT http://127.0.0.1:8000/turf/booking/2/
Content-Type: application/json
Authorization: Basic drf:password@123

{
   "name":"big-b",
   "location":"kochi",
   "email":"big-b@gmail.com",
   "phone_number":"8928380834",
   "duration":"02:10 AM"
}

# api for calling to delete record
###
DELETE http://127.0.0.1:8000/turf/booking/2/
Accept: application/json
Authorization: Basic drf:password@123

