# Generated by Django 6.1.1 on 2026-09-30 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turf_crud', '0002_alter_turf_turf_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('booking_id', models.PositiveIntegerField(editable=False, null=True, unique=True)),
                ('booking_time', models.TimeField(editable=False, null=True)),
                ('purpose', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf_crud.turf')),
            ],
        ),
    ]
