# Generated by Django 6.1.1 on 2026-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('turf_type', models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('basketball', 'Basketball'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('other', 'Other')], default='other', max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
