# Generated by Django 6.1.1 on 2026-09-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='turf_type',
            field=models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('basketball', 'Basketball'), ('badminton', 'Badminton'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('other', 'Other')], default='other', max_length=200),
        ),
    ]
